language: node_js
node_js: stable
install: npm install
script:
 - npm run build

jobs:
  include:
    - stage: tests
      node_js: stable
      script:
        - npm run lint
        - npm run test
        - npm run build
    - stage: semantic release
      if: branch = master AND type = push
      node_js: stable
      script: npm run semantic-release
